apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: postgres:5432
    database: iot_database
    user: grafana_reader
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    secureJsonData:
      password: grafana_password
    editable: true
